[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# DBnet
> mmd.emoticon=`tree`


## 参考

### 具有可微分二值化的实时场景文本检测

### https://arxiv\.org/pdf/1911\.08947

## 背景知识

### 华中科技大学，白翔

#### 廖明辉 华为天才少年 2021

#### OCR半路出家
